[versions]
supabase = "3.6.0"
exposed = "1.2.0"
coroutines = "1.11.0"
atomicfu = "0.33.0"
h2 = "2.3.232"
r2dbc = "1.0.0.RELEASE"
logback = "1.5.35"
ktor = "3.6.0-eap-1648"
slf4j = "2.0.17"
slf4j-android = "2.0.17-0"

[libraries]
compose-icons = { module = "androidx.compose.material:material-icons-extended", version = "1.7.8" }
h2db-h2 =  { module = "com.h2database:h2", version.ref = "h2" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-r2dbc = { module = "org.jetbrains.exposed:exposed-r2dbc", version.ref = "exposed" }
exposed-datetime = { module = "org.jetbrains.exposed:exposed-kotlin-datetime", version.ref = "exposed" }
kotlinx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
ktor-server-di = { module = "io.ktor:ktor-server-di", version.ref = "ktor" }
ktor-server-openapi = { module = "io.ktor:ktor-server-routing-openapi", version.ref = "ktor" }
ktor-server-sse = { module = "io.ktor:ktor-server-sse", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j"}
slf4j-android = { module = "uk.uuid.slf4j:slf4j-android", version.ref = "slf4j-android" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
r2dbc-h2 =  { module = "io.r2dbc:r2dbc-h2", version.ref = "r2dbc" }
supabase-auth = { module = "io.github.jan-tennert.supabase:auth-kt", version.ref = "supabase" }
supabase-postgrest = { module = "io.github.jan-tennert.supabase:postgrest-kt", version.ref = "supabase" }
supabase-realtime = { module = "io.github.jan-tennert.supabase:realtime-kt", version.ref = "supabase" }
